name: codingai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.23
  - scikit-learn>=1.1
  - scipy
  - matplotlib=3.5
  - jupyterlab>=3.5,<3.6
  - pandas=2.2.1
  - unidecode=1.3.8
  - cvxopt=1.3
  - pillow
  - pip
  - pip:
      - jupyterlab-hide-cells==3.0.1
      - nbgitpuller
      - jupyterlab_autorun_cells
